### ISSUE TITLE
What usage does this AST explorer have? 

### ISSUE THREAD

**Issue by mfaani** [SwiftFiddle/swift-ast-explorer#148]
This greatly shows what's happening under the hood in regards to AST generation. 

I also understand it's part of the Swift Compiler/Driver pipeline. But what usage does it have for developers? I was trying to find something in the README.md but I couldn't. 

Is it just a demonstration tool or you were seeking something else and had to create this explorer for it?

**Comment by kishikawakatsumi** [comment]
This tool displays the results of running [SwiftSyntax](https://github.com/apple/swift-syntax), a parser used internally by the Swift compiler.

SwiftSyntax is not only used internally by the compiler, but also by static analysis tools such as [swift-format](https://github.com/apple/swift-format) and [SwiftLint](https://github.com/realm/SwiftLint), and code generators such as [Sourcery](https://github.com/krzysztofzablocki/Sourcery).

In addition, macros will soon be introduced to Swift, and SwiftSyntax will be used to implement macros.
The authors of these metaprogramming tools use SwiftSyntax, so we need a tool to easily see the results of how SwiftSyntax parses the Swift code.
