### ISSUE TITLE
Structure tooltip placement prevents disclosure triangle interaction

### ISSUE THREAD

**Issue by dafurman** [SwiftFiddle/swift-ast-explorer#524]
I'm unable to collapse structure components using the disclosure triangles, because the tooltips that show up cover them up as soon as I hover over the triangles.

https://github.com/SwiftFiddle/swift-ast-explorer/assets/10556242/c5e5ad7f-11a2-4825-9ea6-db935560de9d

**Comment by dafurman** [comment]
Ah, I did realize I can just click on the text itself to collapse / expand, so there's at least a workaround 👍, though this was less intuitive to me.

**Comment by kishikawakatsumi** [comment]
The Tooltip is intentionally displayed close enough so that you can select or copy the text in the Tooltip (so that the Tooltip does not disappear when you try to move the mouse over the Tooltip). Thanks for the report as it is definitely not intuitive and could be improved.
